[[feedback]]
text = """
The Research Software Engineering Group has been of great help to me in
starting to use Git and organizing my code.
"""

[[feedback]]
text = """
The execution time for my script went down from 4 weeks to below an hour which
was really cool!
"""
